### ISSUE TITLE
Замечания по работе №4

### ISSUE THREAD

**Issue by AndriiLitvin** [barbarosa30/barbarosa30.github.io#3]
## http://joxi.ru/vAWZzP3sk1M6P2

1) бордер с box-shadow он должен быть только в менюшки и всего блока с контенторм.
2) тут убери минусовые маргины. и у менюшки убери 10рх высоты. когда делаешь паддинг он розширяет блок. можно еще выравнивать вместо паддинга  line-height.
3)сделай какой то эфект по ховеру
4) триугольник меньше. его можно сделать через спецсимволы.

**Comment by barbarosa30** [comment]
Исправил

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
